### ISSUE TITLE
Add pretty print function for JSON objects

### ISSUE THREAD

**Issue by fjalars** [logileifs/shellson#6]
It would be super nice if there was a pretty print functionality (flag) in the tool.

**Comment by gsailer** [comment]
This is really [simple](https://stackoverflow.com/a/12944035) to implement. You would just add indent=4 to the json.dumps(output) line in main and add a new flag in the argparser.
The piping of shellson calls would not be impacted by this change as json.loads does not care about the format of the json.
Further the tests should also not be impacted because currently there are only simple test cases.
The question here is if this should maybe be default behaviour of the tool.

**Comment by logileifs** [comment]
done https://github.com/logileifs/shellson/pull/8
